[package]
name = "rindrive_gui"
version.workspace = true
authors.workspace = true
edition.workspace = true

[package.metadata.dist]
dist = false

[dependencies]
rindrive_core = { workspace = true }
rindrive_i18n = { workspace = true }
iced = { workspace = true }
rfd = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
